name: Build Extension

on:
  push:
    branches: [ "*", "!main" ]
  workflow_dispatch:

env:
  NODE_VERSION: 20.18.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm run install:all
      
      - name: Build extension
        run: npm run vsix
      
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-vsix
          path: bin/*.vsix
          if-no-files-found: error